package api

const (
	//API_URL                     = "http://localhost"
	API_URL                     = "http://195.154.84.18:20080"
	ROUTE_NEW_PROGRAMME         = "v1/programme/new"
	ROUTE_LOAD_PROGRAMME        = "v1/programme/load"
	ROUTE_UNSET_PROGRAMME       = "v1/programme/unset"
	ROUTE_SAVE_PROGRAMME        = "v1/programme/save"
	ROUTE_JUMPUP_PROGRAMME      = "v1/programme/jump/up"
	ROUTE_JUMPDOWN_PROGRAMME    = "v1/programme/jump/down"
	ROUTE_MOVE_PROGRAMME        = "v1/programme/move"
	ROUTE_SCAN_PROGRAMME        = "v1/programme/scan"
	ROUTE_EXPLORE_PROGRAMME     = "v1/programme/explore"
	ROUTE_DESTROY_PROGRAMME     = "v1/programme/destroy"
	ROUTE_REBUILD_PROGRAMME     = "v1/programme/rebuild"
	ROUTE_STATUS_GRID           = "v1/grid"
	ROUTE_STATUS_PROGRAMME      = "v1/programme/infos"
	ROUTE_CAPTURE_CELL_DATA     = "/v1/programme/capture/cellule/data"
	ROUTE_CAPTURE_CELL_ENERGY   = "/v1/programme/capture/cellule/energy"
	ROUTE_CAPTURE_TARGET_DATA   = "/v1/programme/capture/target/data"
	ROUTE_CAPTURE_TARGET_ENERGY = "/v1/programme/capture/target/energy"
	ROUTE_EQUILIBRiUM           = "/v1/programme/equilibrium"
	ROUTE_PUSH_FLAG             = "/v1/programme/push/flag"
)
