package api

const (
	//API_URL                          = "http://localhost"
	API_URL                          = "http://195.154.84.18:20080"
	ROUTE_NEW_PROGRAMME              = "v1/programme/new"
	ROUTE_LOAD_PROGRAMME             = "v1/programme/load"
	ROUTE_UPGRADE_PROGRAMME          = "v1/programme/upgrade"
	ROUTE_UNSET_PROGRAMME            = "v1/programme/unset"
	ROUTE_MOVE_PROGRAMME             = "v1/programme/move"
	ROUTE_SCAN_PROGRAMME             = "v1/programme/scan"
	ROUTE_GET_CELLULE_LOG            = "v1/programme/cellule/log"
	ROUTE_EXPLORE_PROGRAMME          = "v1/programme/explore"
	ROUTE_DESTROY_PROGRAMME          = "v1/programme/destroy"
	ROUTE_REBUILD_PROGRAMME          = "v1/programme/rebuild"
	ROUTE_STATUS_GRID                = "v1/grid"
	ROUTE_STATUS_PROGRAMME           = "v1/programme/infos"
	ROUTE_CAPTURE_CELL_DATA          = "v1/programme/capture/cellule/data"
	ROUTE_CAPTURE_CELL_ENERGY        = "v1/programme/capture/cellule/energy"
	ROUTE_CAPTURE_TARGET_DATA        = "v1/programme/capture/target/data"
	ROUTE_CAPTURE_TARGET_ENERGY      = "v1/programme/capture/target/energy"
	ROUTE_EQUILIBRiUM                = "v1/programme/equilibrium"
	ROUTE_PUSH_FLAG                  = "v1/programme/push/flag"
	ROUTE_SAVE_PROGRAMME             = "v1/programme/save"
	ROUTE_DESTROY_ZONE               = "v1/programme/destroy/zone"
	ROUTE_NAVIGATION_PROGRAMME_START = "v1/programme/navigation"
	ROUTE_NAVIGATION_PROGRAMME_STOP  = "v1/programme/navigation/stop"
	ROUTE_EXPLORATION_PROGRAMME_STOP = "v1/programme/exploration/stop"
	ROUTE_STOP_MOVE_PROGRAMME        = "v1/programme/stop/move"
	ROUTE_ESTIMATE_MOVE_PROGRAMME    = "v1/programme/estimate/move"
)
